# Generated by Django 3.2.6 on 2021-08-30 15:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='images/default.jpg', upload_to=users.models.get_upload_path),
        ),
    ]
