# Generated by Django 3.2.6 on 2021-09-01 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tweets.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_options'),
        ('locations', '0002_auto_20210901_0201'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('comments', models.IntegerField(default=0)),
                ('retweets', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tweets.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='TweetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=25, unique=True)),
                ('categories', models.ManyToManyField(to='categories.Category')),
                ('trending_countries', models.ManyToManyField(to='locations.Country')),
            ],
        ),
        migrations.CreateModel(
            name='TweetImage',
            fields=[
                ('image', models.ImageField(default='images/default.jpg', upload_to=tweets.models.get_tweetimage_upload_path)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.tweet')),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tweets.TweetTag'),
        ),
        migrations.CreateModel(
            name='BigTweet',
            fields=[
                ('featured_image', models.ImageField(default='images/default.jpg', upload_to=tweets.models.get_bigtweet_upload_path)),
                ('header', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tags', models.ManyToManyField(blank=True, to='tweets.TweetTag')),
            ],
        ),
    ]
