# Generated by Django 3.2.6 on 2021-09-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210901_0201'),
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweettag',
            name='trending_countries',
            field=models.ManyToManyField(blank=True, to='locations.Country'),
        ),
    ]
