# Generated by Django 3.2.6 on 2021-09-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
        ('tweets', '0002_alter_tweettag_trending_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigtweet',
            name='categories',
            field=models.ManyToManyField(blank=True, to='categories.Category'),
        ),
    ]
