# Generated by Django 3.2.6 on 2021-09-02 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
        ('tweets', '0004_bigtweet_featured_paramenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigtweet',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='bigtweet',
            name='featured_paramenter',
        ),
        migrations.RemoveField(
            model_name='bigtweet',
            name='tags',
        ),
        migrations.AddField(
            model_name='bigtweet',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
        migrations.AddField(
            model_name='bigtweet',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tweets.tweettag'),
        ),
    ]
