# Generated by Django 3.2.6 on 2021-09-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20210902_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigtweet',
            name='header',
            field=models.CharField(max_length=200),
        ),
    ]
